## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml

name: filebeat

filebeat.inputs:
  - type: filestream
    id: gocourse-log-input
    enabled: true
    paths:
      - "/var/log/filebeat/service/*.log"
      - "/app/*.log"
    fields:
      environment: Development
    tags: ["gocourse"]
    prospector.scanner.exclude_files: ['.gz$']
    multiline:
      type: pattern
      pattern: "^{"
      negate: true
      match: after

logging.level: debug

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

setup.template.name: "logs-service"
setup.template.pattern: "logs-service-*"
setup.kibana.host: kibana:5601
setup.template.settings:
  index.number_of_shards: 1

processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: false
      add_error_key: true

filebeat.shutdown_timeout: 5s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}
  index: "logs-service-%{+yyyy.MM.dd}"

fields_under_root: true
fields:
  host.ip: 127.0.0.1
